class Categories:
    cb = 'cb'
    misc = 'misc'


class HelpDoc(dict):
    def __init__(self, help_txt, brief: str, description='', usage='', example=''):
        if not description:
            description = self.descriptify(brief)
        super().__init__(
            help=help_txt,
            brief=brief,
            description=description,
            usage=usage,
            example=example,
        )

    def descriptify(self, s):
        return s[0].upper() + s[1:] + '.'


help_doc = dict(
    battle=HelpDoc(Categories.cb, 
                'Start a Mock Scoresheet in this channel with two team names and the size of people per team. You can also ping the corresponding team role.',
                '**Usage:** battle (Team1) (Team2) (Size)', 
                '**Example:** battle TeamThea @Team Aqua 5'),
    send=HelpDoc(Categories.cb, 
                'Sends in the mentioned/selected player for the specified team.',
                '**Usage:** send (@Player) (TeamName)', 
                '**Example:** send @superhylia TeamCapulus'),
    replace=HelpDoc(Categories.cb, 
                'Replaces current player with the mentioned/selected player.', 
                '**Usage:** replace (@Player) (TeamName)', 
                '**Example:** replace Oracle TeamCapulus'),
    end=HelpDoc(Categories.cb, 
                'End the game with characters and stocks for both teams.',
                '**Usage:** end (Char1)[AltNum] (StocksTaken1) (Char2)[AltNum] (StocksTaken2)', 
                '**Example:** end Mario4 3 DK2 1'),
    endlag=HelpDoc(Categories.cb,
                'Prematurely end the game with characters and stocks for both teams due to lag or disconnection.',
                '**Usage:** end (Char1)[AltNum] (StocksTaken1) (Char2)[AltNum] (StocksTaken2)',
                '**Example:** end Mario4 3 DK2 1'),
    resize=HelpDoc(Categories.cb, 
                'Resize the size of players per team of the crew battle.', 
                '**Usage:** resize (Size)',
                '**Example:** resize 3'),
    undo=HelpDoc(Categories.cb, 
                'Undoes the last action taken by the bot.',
                '**Usage:** undo', 
                '**Example:** undo'),
    timerstock=HelpDoc(Categories.cb, 
                'Lose a stock on your team's side due to timing out if you've been sent in: otherwise, if a team is specified, the last player on the selected team will lose a stock due to the timer.''',
                '**Usage:** timerstock [TeamName]',
                '**Example:** timerstock TeamThea'),
    forfeit=HelpDoc(Categories.cb,
                'Forfeit the crew battle on your team's behalf if you've been sent in: otherwise, if a team is specified, the selected team will forfeit the crew battle.''',
                '**Usage:** forfeit [TeamName]',
                '**Example:** forfeit TeamCapulus'),
    status=HelpDoc(Categories.cb, 
                'Prints the current status of the crew battle with an overview of players, stocks taken, lobby ID, and stream.',
                '**Usage:** status',
                '**Example:** status'),
    chars=HelpDoc(Categories.cb,
                'Prints all characters, their compatible nicknames, and all of their emojis via your DMs.', 
                '**Usage:** chars',
                '**Example:** battle TeamThea @Team Aqua 5'),
    clear=HelpDoc(Categories.cb,
                'Clears the current crew battle in the channel.',
                '**Usage:** clear',
                '**Example:** clear'),
    confirm=HelpDoc(Categories.cb, 
                'Confirm the final scoresheet is correct once the battle is over.',
                '**Usage:** confirm',
                '**Example:** confirm'),
    char=HelpDoc(Categories.cb, 
                'Prints the character's corresponding emojis. This is a good way to test what emoji will be used on the scoresheet with the `end` command.''',
                '**Usage:** char (Char1)[AltNum]',
                 '**Example:** char Sephiroth7'),
    arena=HelpDoc(Categories.cb, 
                'Prints the arena information: if the arena ID/pass is specified, the arena will be set.',
                '**Usage:** arena [ID/Pass]',
                '**Example:** arena LFLTC/2020'),
    stream=HelpDoc(Categories.cb, 
                'Prints the stream information: if the streamlink is specified, the stream will be set.',
                '**Usage:** stream [StreamLink]',
                '**Example:** stream https://twitch.tv/LifelightCafe'),
    timer=HelpDoc(Categories.cb, 
                'Prints the time in minutes and seconds since the last match finished.',
                '**Usage:** timer',
                '**Example:** timer'),
    guide=HelpDoc(Categories.misc,
                'Provides the link to the usage guide for the bot.',
                '**Usage:** guide',
                '**Example:** guide'),
    coin=HelpDoc(Categories.misc,
                'Flips a coin: if a user is mentioned, it will ask them to choose heads or tails.',
                 '**Usage:** coin [@User]',
                 '**Example:** coin @superhylia'),
    use_ext=HelpDoc(Categories.cb,
                'Use the extension period to send in the next player on your team's behalf if you've been sent in: otherwise, if a team is specified, the selected team will use the extension period.''',
                '**Usage:** use_ext [TeamName]',
                '**Example:** use_ext TeamAqua'),
    ext=HelpDoc(Categories.cb, 
                'Prints whether or not either team has used their extension period.',
                '**Usage:** ext',
                '**Example:** ext'),
    countdown=HelpDoc(Categories.cb,
                'Counts down for 3 seconds: if a time is specified, it will count down from that time in seconds.',
                '**Usage:** countdown [Time]',
                '**Example:** countdown 10'),
    credits=HelpDoc(Categories.misc,
                'Provides the credits for the bot.',
                '**Usage:** credits',
                '**Example:** credits'),
    print_all_emojis=HelpDoc(Categories.misc, 
                'TEST.', '**Usage:** battle Team1 Team2 Size', '', '**Example:** battle TeamThea @Team Aqua 5'),    
    thank=HelpDoc(Categories.misc,
                'Thanks the original bot developer, AlexJett!',
                '**Usage:** thank',
                '**Example:** thank'),
    stagelist=HelpDoc(Categories.misc,
                'Provides an image of the stagelist used in crew battles.',
                '**Usage:** stagelist',
                '**Example:** stagelist'),
    invite=HelpDoc(Categories.misc,
                'Provides an invite to the Lifelight Café and Steamy League Discord servers.',
                '**Usage:** invite',
                '**Example:** invite'),
)
